import type { Metadata } from "next";
import Sidebar from "./_components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <div>
        <Sidebar />
      </div>
      <div className="ml-[calc(16rem+1rem)]">{children}</div>
    </div>
  );
}
